# Dockerfile.celery
FROM python:3.10-slim

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /app

COPY pyproject.toml uv.lock ./

RUN uv sync --frozen --no-cache

COPY . .

CMD ["/app/.venv/bin/celery", "-A", "utils.celery_app", "worker", "--loglevel=info", "--pool=solo"]